ALTER TABLE flows_v3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE runs_v3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE steps_v3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks_v3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE metadata_v3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE artifact_v3 ENABLE ROW LEVEL SECURITY;
